eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9090
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service/
          predicates:
            - Path=/authentication-service/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

